### ISSUE TITLE
Spine Layer is set to UI Layer

### ISSUE THREAD

**Issue by dexterdeluxe88** [playcanvas/playcanvas-spine#16]
The layer for spine rendering gets set to UI layer with this code in spine.js:

`this._layers = [pc.LAYERID_UI];`

Since one also wants to have UI rendererd over the spine characters, please consider to make this changeable via attributes.

Best,
Rene

**Comment by yaustar** [comment]
The property is exposed so you can change it in a script: https://github.com/playcanvas/playcanvas-spine/blob/master/src/plugin/spine.js#L550

It is a bit odd to have the UI as the default layer though. There might be some reasoning behind it at the time.

**Comment by dexterdeluxe88** [comment]
Thanks for the quick response Steven!

Maybe this features (as well as other basics, like [animation callbacks](https://forum.playcanvas.com/t/spine-plugin-animation-complete-callback/8413/7) etc.) deserve a small documentation at some point ;)

Best,
Rene

**Comment by daredevildave** [comment]
The layer defaults to UI as this is the only in-built layer that is sorted by draworder. It's expected that user's can change the layer, just make sure the new layer is set to use `pc.SORTMODE_MANUAL`

**Comment by dexterdeluxe88** [comment]
Just for reference, I've managed to set the layer like this:

`    this.entity.spine.spine.layers = [this.app.scene.layers.getLayerByName("MyCustomLayer").id];
`

or you can do it via a small helper script:

```
var SetSpineLayer = pc.createScript('setSpineLayer');

SetSpineLayer.attributes.add('layerNames', { type: 'string', array: true});

// initialize code called once per entity
SetSpineLayer.prototype.initialize = function() 
{
    var layers = [];
    
    var layerComp = this.app.scene.layers;
    
    this.layerNames.forEach(function(layerName)
    {
        layers.push(layerComp.getLayerByName(layerName).id);
    });
    
    this.entity.spine.spine.layers = layers;
};
```
Make sure that "MyCustomLayer" is also added to the camera's layers, so it gets rendered.

**Comment by willeastcott** [comment]
Cool. Thanks for sharing.
