### ISSUE TITLE
Disable rendered spine model when Entity is disabled

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/playcanvas-spine#2]
When the Entity that displays a spine model is disabled we should also hide the rendered spine model.

**Comment by willeastcott** [comment]
I just ran the 'knight' example and opened the JS console and did:

```
pc.app.root.findComponent('spine').entity.enabled = false
```

This correctly hid the character, removing it from the scene's layers (the onDisable for the spine component was successfully called).

The following reactivated it:

```
pc.app.root.findComponent('spine').entity.enabled = true
```

So I'm closing this. Please reopen if you think I have misunderstood.
