### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by MoserAlex** [playcanvas/playcanvas-spine#23]
I noticed that spine entities don't get freed in the memory. I used [this project](https://playcanvas.com/editor/scene/834432) to reproduce this issue by having two scenes with one spine object each and you can switch between them. After each scene change, the previous spine entity can't get fully deleted. You can check this out by using the Memory Allocation Timeline of the chrome debugging tools. I explain it in further detail in [this forum post](https://forum.playcanvas.com/t/memory-leaks-of-spine-component/11398).

**Comment by willeastcott** [comment]
This should have been fixed by https://github.com/playcanvas/playcanvas-spine/pull/24

If you find this not to be the case, please reopen this issue.
