### ISSUE TITLE
Awesome!!! 

### ISSUE THREAD

**Issue by inglesuniversal** [playcanvas/playcanvas-spine#25]
Do you have a version of Super SpineBoy for mobile? (safari and mobile chrome)

Your version apparently only works on desktop browsers.

Regards

**Comment by willeastcott** [comment]
Are you referring to this project:

https://playcanvas.com/project/371371/overview/super-spineboy

If so, I think it needs updating to use the latest runtime from this repo - seems a bit broken at the moment.

The only reason it works on desktop browers is that the author of this port didn't get around to adding touch controls. There's nothing too difficult about that. The core game should work just find on mobile though.

**Comment by inglesuniversal** [comment]
I've seen a lot of interest from my students on using this demo game on their phones.

How could I request that the code be updated for mobile usage?

Best regards.

**Comment by willeastcott** [comment]
Yeah, it would be cool if it was updated to work perfectly on mobile. It would take a bit of effort to make that happen though. My team doesn't really have the bandwidth to work on it. And it doesn't sound like you would want to pay a contractor to do this work. So I don't really have any great suggestions right at the moment, I'm afraid.

**Comment by inglesuniversal** [comment]
oh do not worry about that. Which brings me to the next question. 

One of the reasons why I haven't built any games on PlayCanvas so far, is that I would love to have a guided tour or video giving step by step instructions on how to accomplish something very basic.

I see the same thing on Phaser, where they have a section for examples, but not an overall tour or basic introduction.

That would be amazing.

Best regards

**Comment by yaustar** [comment]
Have you tried the Keepy Up series of tutorials? https://developer.playcanvas.com/en/tutorials/keepyup-part-one/

**Comment by mvaligursky** [comment]
I'll close this as there's no work needed that is related to this repo.
