### ISSUE TITLE
Attaching listeners to AnimationState

### ISSUE THREAD

**Issue by jadomingo** [playcanvas/playcanvas-spine#32]
Hi, I'm not sure where to ask questions regarding the PC runtime for Spine so I'm asking here.

Can you provide an example of how to use _addListener()_? The Spine User Guide wasn't able to help me in this regard.

**Comment by slimbuck** [comment]
cc @mvaligursky

**Comment by mvaligursky** [comment]
I have not tried it .. but perhaps experiment with this example we have:
https://github.com/playcanvas/playcanvas-spine/blob/10b4c2b6d6c10784a5bd60ce1a5cb1406ced58ef/examples/hero.html#L131

you should be able to addListener to hero.spine.states[1] that's created there I think.

**Comment by jadomingo** [comment]
It took some digging around the PlayCanvas forums but I managed to get it to work.

```
this.entity.spine.state.addListener({event: function(track,event) {
        if (event.data.name == "fire") {
            console.log("fire");
        }
} });
```

Thanks for pointing me in the right direction!

**Comment by mvaligursky** [comment]
good news!
