### ISSUE TITLE
Mention required "Power Of Two" export option.

### ISSUE THREAD

**Issue by forcepusher** [playcanvas/playcanvas-spine#38]
This took a fair bit of head-scratching, so I'll post it here to avoid that problem in the future.
Since PlayCanvas resizes the textures to nearest power of two by default, this "Power of two" Spine export option has to be used.
![image](https://user-images.githubusercontent.com/5948501/92817365-b144d400-f3f0-11ea-8a1f-09f8f39ff19e.png)
(otherwise, image resizing has to be disabled in PlayCanvas Asset Task settings)

**Comment by willeastcott** [comment]
You don't have to have the Editor resize your textures on import. Just go to `Settings` -> `Asset Tasks` and uncheck `Textures POT`.
