### ISSUE TITLE
Import playcanvas-spine to Scripts 2.0

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/playcanvas-spine#4]
Thinking it is time! :)

Now that PlayCanvas has a 2D api, Spine complements well as a 2D animation solution.

**Comment by daredevildave** [comment]
This code already uses the Scripts 2.0 API?

**Comment by leonidaspir** [comment]
Great, got misled by the Readme, which needs updating. Also the installation instructions need, as the following file is missing (not required?) from that folder:

> Add the library script lib/patch.js to your project and add it to your Script Priority list.

**Comment by daredevildave** [comment]
Good point. I've updated the Readme.
