### ISSUE TITLE
Basis compressed textures for the atlas throws code errors

### ISSUE THREAD

**Issue by yaustar** [playcanvas/playcanvas-spine#50]
Example: https://playcanvas.com/project/826377/overview/spine-basis-compression

Thread: https://forum.playcanvas.com/t/playcanvas-1-46-1-playcanvas-spine-console-error/21679

**Comment by mvaligursky** [comment]
@slimbuck - any ideas about this?

**Comment by yaustar** [comment]
Fixed by PR above
