### ISSUE TITLE
Support for Spine 4.x now that it's stable?

### ISSUE THREAD

**Issue by ChristianTucker** [playcanvas/playcanvas-spine#52]
Just wondering if there's any plans to support 4.x now that it's been promoted to stable.

**Comment by yaustar** [comment]
There are currently no short term plans unfortunately

**Comment by shreddox** [comment]
The latest versions of Spine have introduced vital new features, e.g. a new graph editor.
Working with the old 3.8 is slowly becoming an issue in our pipeline.

What's currently holding the plugin update back?

**Comment by mvaligursky** [comment]
The priority against other tasks are holding it back at the moment.
But we do accept community contributions, if somebody wants to pick it up, we'd be very happy to review it and get it to a final form if needed.

**Comment by willeastcott** [comment]
Looks like a (nearly complete?) PR is available here: https://github.com/playcanvas/playcanvas-spine/pull/57

Wondering how close to working that is, @mvaligursky.

**Comment by mvaligursky** [comment]
Not very close .. see the detail in the PR.
