### ISSUE TITLE
Minor Issue: Mesh constructor takes a GraphicsDevice as a parameter

### ISSUE THREAD

**Issue by epreston** [playcanvas/playcanvas-spine#70]
### Description

Engine Build: 1.6.5

Deprecation warning:

> DEPRECATED: Mesh constructor takes a GraphicsDevice as a parameter, and it was not provided.

From the following line:

https://github.com/playcanvas/playcanvas-spine/blob/71ec3c5d9a534cf05e6b5a20db6aa55198aad842/src/spine.js#L543C38-L543C38

### Resolution

Should be changed to the following or similar:

```js
var mesh = new pc.Mesh(pc.graphicsDevice);
```

Deprecated 10 months ago.

**Comment by willeastcott** [comment]
I think it'd be:

```javascript
var mesh = new pc.Mesh(this._app.graphicsDevice);
```

**Comment by epreston** [comment]
Will clarified the timeline for the Mesh constructor signature change here:  https://github.com/playcanvas/playcanvas-spine/pull/73#discussion_r1287148079

It's been 3 years since 1.27

**Comment by epreston** [comment]
Remediation plan here: https://github.com/playcanvas/playcanvas-spine/pull/73#discussion_r1285579429
