### ISSUE TITLE
I found that he couldn't complete my attack animation.

### ISSUE THREAD

**Issue by grasp-Cat** [playcanvas/playcanvas-spine#76]
I think the wait animation is played before the attack animation is complete, causing the gun to drop directly.
how to solve this problem?
![1](https://github.com/playcanvas/playcanvas-spine/assets/111098875/ac1c604f-1da5-46aa-b3e9-300541cdf3ef)
![0](https://github.com/playcanvas/playcanvas-spine/assets/111098875/8f27f020-4a42-4e76-a0f4-081eb1cb2a7b)

**Comment by mvaligursky** [comment]
I think this is a question more suitable for the Spine forum, where questions on how to use the Spine library are discussed. This repo only provides compatibility rendering layer for PlayCanvas.
